---
title: "virtual_species_sim"
author: 'Luke'
format: gfm+emoji
editor: visual
---

```{r setup}
#| include: false

file_name <- knitr::current_input()

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.rmarkdown$", "", basename(file_name)), "/", sep = "")
)

ggplot2::theme_set(ggplot2::theme_classic(base_size = 10))
```

## Virtual species

```{r}
library(virtualspecies)
library(raster)

# 
f1 = raster(ncol=50, nrow=50, xmn=0, xmx=50, ymn=0, ymx=50)
f2 = raster(ncol=50, nrow=50, xmn=0, xmx=50, ymn=0, ymx=50)

values(f1) = runif(ncell(f1))
values(f2) = runif(ncell(f2))

stackf = stack(f1,f2)

names(stackf) = c("f1","f2")
```

```{r}
my.parameters = formatFunctions(f1 = c(fun = 'dnorm', mean = 0, sd = 0.2),
                                f2 = c(fun = 'quadraticFun', a = -1, b = 2, c = 0))

my.first.species = generateSpFromFun(raster.stack = stackf,
                                              parameters = my.parameters,
                                              plot = TRUE)
```
